# Load-order manifest: the only file allowed to `require`. mruby has no
# `require`, so the mruby build compiles these same files in this same order.
require_relative "yara/ast"
require_relative "yara/diagnostics"
require_relative "yara/environment"
require_relative "yara/messages"
require_relative "yara/rust_format"
require_relative "yara/types"
require_relative "yara/lexer"
require_relative "yara/translations"
require_relative "yara/parser"
require_relative "yara/parser/statements"
require_relative "yara/parser/expressions"
require_relative "yara/resolver"
require_relative "yara/builtins"
require_relative "yara/methods"
require_relative "yara/typechecker"
require_relative "yara/typechecker/expressions"
require_relative "yara/typechecker/statements"
require_relative "yara/typechecker/calls"
require_relative "yara/typechecker/classes"
require_relative "yara/typechecker/methods"
require_relative "yara/cli"
